# This is a basic workflow to help you get started with Actions

name: Netlify Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [created]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: "Checkout Source Code"
      
      - name: Setup Node.js environment with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

    # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          npm install --production
          npm run build
        
      - name: Deploy to Netlify Production
        uses: nwtgck/actions-netlify@v1.1.3
        with:
          publish-dir: './dist'
          production-branch: main
          deploy-message: '${{ github.event.release.tag_name }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
